apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-grpc-service
  name: udaconnect-location-grpc-service
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30003
  selector:
    service: udaconnect-location-grpc-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-grpc-service
  name: udaconnect-location-grpc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-grpc-service
  template:
    metadata:
      labels:
        service: udaconnect-location-grpc-service
    spec:
      containers:
      - image: vincentbiasa6767/udaconnect-location-grpc-service:implement-kafka
        name: udaconnect-location-grpc-service
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "258m"
            memory: "128Mi"
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
