apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-consumer-service
  name: udaconnect-location-consumer-service
spec:
  ports:
  - name: "5000"
    port: 5000
    protocol: TCP
  selector:
    service: udaconnect-location-consumer-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-consumer-service
  name: udaconnect-location-consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-consumer-service
  template:
    metadata:
      labels:
        service: udaconnect-location-consumer-service
    spec:
      containers:
      - image: vincentbiasa6767/udaconnect-location-consumer-service:master
        name: udaconnect-location-consumer-service
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
